# Generated by Django 5.1.7 on 2025-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmvideo',
            name='violations',
        ),
        migrations.AddField(
            model_name='algorithmvideo',
            name='violation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='algorithmvideo',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='processed/video/'),
        ),
        migrations.AlterField(
            model_name='algorithmvideo',
            name='video',
            field=models.FileField(upload_to='uploads/video/'),
        ),
    ]
