# Generated by Django 5.1.7 on 2025-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_algorithmvideo_violations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmvideo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
