# Generated by Django 5.1.7 on 2025-05-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_algorithmvideo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionmodel',
            name='media_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
