# Generated by Django 5.1.7 on 2025-05-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recognitionmodel_media_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitionmodel',
            name='cropped_images',
        ),
        migrations.AlterField(
            model_name='recognitionmodel',
            name='processed_media',
            field=models.FileField(blank=True, null=True, upload_to='processed/detection/'),
        ),
    ]
