# Generated by Django 5.1.7 on 2025-05-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_recognitionmodel_cropped_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionmodel',
            name='cropped_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recognitionmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recognitionmodel',
            name='processed_media',
            field=models.FileField(blank=True, null=True, upload_to='processed/recognition/'),
        ),
    ]
